# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        UserBundle\Entity\User: sha512
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    role_hierarchy:
        ROLE_VISITEUR: ROLE_USER
        ROLE_COMPTABLE: ROLE_USER
        ROLE_ADMIN:       [ROLE_VISITEUR, ROLE_COMPTABLE]
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
            fos_userbundle:
                id: fos_user.user_provider.username_email
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            logout:   true
            anonymous:   true
    access_control:
        # redirection au /login si l'utilisateur n'est pas authentifié
        # TODO: Autoriser ou non l'accès à certaines routes en fonction des roles
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/etatFrais, roles: ROLE_COMPTABLE }
        - { path: ^/etat, roles: ROLE_VISITEUR}