<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param mixed $id
     * @param null $lockMode
     * @param null $lockVersion
     * @return null|object
     */
    public function find($id, $lockMode = null, $lockVersion = null)
    {
        return parent::find($id, $lockMode, $lockVersion); // TODO: Change the autogenerated stub
    }

    /**
     * Retourne les informations d'un visiteur
     * @param $login
     * @param $pwd
     * @return null|object
     */
    public function getInfosVisiteurs($login, $pwd){
        return $this->findOneBy(array('username' => $login,
            'password' => $pwd));

    }

    /**
     * Retourne tous les utilisateurs en fonction de leur role
     * @param string $role
     * @return array
     */
    public function findByRole($role)
    {
        return $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%'.$role.'%')
            ->getQuery()->getArrayResult();
    }

}
