<?php

namespace GSBBundle\Repository;

/**
 * EtatFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatFraisRepository extends \Doctrine\ORM\EntityRepository
{
}
