<?php

namespace GSBBundle\Repository;

/**
 * fichefraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fichefraisRepository extends \Doctrine\ORM\EntityRepository
{
}
