<?php

namespace GSBBundle\Repository;

/**
 * FraisForfatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisForfatRepository extends \Doctrine\ORM\EntityRepository
{
}
