<?php

namespace GSBBundle\Repository;

/**
 * fraisforfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fraisforfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
