<?php

namespace GSBBundle\Repository;

/**
 * lignefraisforfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lignefraisforfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
