<?php

namespace GSBBundle\Repository;

/**
 * lignefraishorsforfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lignefraishorsforfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
